awesome-academy/dn_ruby_oe-intern-football_bet_and_new_system

.gitignore
.sun-ci.yml
app/controllers/sessions_controller.rb
app/helpers/sessions_helper.rb
app/models/user.rb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb
app/views/sessions/new.html.erb
config/locales/en.yml
config/locales/vi.yml
config/routes.rb
db/migrate/20220316063637_add_remember_digest_to_users.rb
db/schema.rb

Log In And Log Out
- Add feature log in, log out
- add session, cookie
- add remember me

Log In/Out

---

app/models/currency.rb
db/seeds.rb

#7: Modify model & seed
• [#47134](https://edu-redmine.sun-asterisk.vn/issues/47134)
What
- Modify model currency & add seed for currency
How
- Add enum,  scope, validates
- modify seed

Show user history currencies and create new currency

---

app/controllers/currencies_controller.rb
app/views/currencies/_type_currencies.html.erb
app/views/currencies/new.html.erb
config/locales/en.yml
config/locales/vi.yml
config/routes.rb

• [#47137](https://edu-redmine.sun-asterisk.vn/issues/47137)
What
- Feature Payment & withdrawal for user
How
-Create form currencies with field amount and hidden field currencies_type_id
- Handle create in currencies_controller

Create form payment anhd withdrawal

---

app/models/bet.rb
app/models/soccer_match.rb
app/models/user.rb
app/models/user_bet.rb
db/migrate/20220316095220_create_bets.rb
db/migrate/20220316095721_create_user_bets.rb
db/schema.rb
db/seeds.rb

• [#47137](https://edu-redmine.sun-asterisk.vn/issues/47133)
What
- Modify file Seed and models
How
- Add seed data soccer match, Bet
- modify table CSDL
- modify model

Modify file Seed and models

---

app/helpers/soccer_match_helper.rb
app/models/soccer_match.rb
app/models/tournament.rb
app/views/soccer_matches/_soccer_match.html.erb

fix show tournament

---

app/controllers/admin/base_controller.rb
app/controllers/admin/soccer_matches_controller.rb
app/controllers/sessions_controller.rb
app/helpers/soccer_match_helper.rb
app/views/admin/soccer_matches/_soccer_match.html.erb
app/views/admin/soccer_matches/index.html.erb
app/views/layouts/_asider.html.erb
app/views/shared/_asider_admin.html.erb
app/views/shared/_asider_user.html.erb
config/locales/en.yml
config/locales/vi.yml
config/routes.rb

• [#47566](https://edu-redmine.sun-asterisk.vn/issues/47566)
What
- create admin namespace
How
- show admin page after loged in by admin account

Create admin namespace

---

app/controllers/bets_controller.rb
app/controllers/user_bets_controller.rb
app/helpers/user_bets_helper.rb
app/models/user.rb
app/models/user_bet.rb
app/views/bets/_bet.html.erb
app/views/bets/_bet_infor.html.erb
app/views/shared/_asider_user.html.erb
app/views/soccer_matches/_soccer_match.html.erb
app/views/user_bets/_user_bet.html.erb
app/views/user_bets/index.html.erb
app/views/user_bets/new.html.erb
config/locales/en.yml
config/locales/vi.yml
config/routes.rb
db/migrate/20220323142832_remove_soccer_matchs_from_user_bets.rb
db/migrate/20220323143137_add_bet_to_user_bet.rb
db/schema.rb

• [#47133](https://edu-redmine.sun-asterisk.vn/issues/47133)
What
- User bet a soccer match
How
- click bets to select type bet
- Create form new to user bet amount (new & index)
- Show list history user bet

User bet soccer match

---

app/controllers/admin/user_bets_controller.rb
app/helpers/soccer_match_helper.rb
app/models/bet.rb
app/views/admin/soccer_matches/_soccer_match.html.erb
app/views/admin/user_bets/_user_bet.html.erb
app/views/admin/user_bets/index.html.erb
config/locales/en.yml
config/locales/vi.yml
config/routes.rb
db/seeds.rb

• [#47127](https://edu-redmine.sun-asterisk.vn/issues/47127)
What
-  Show User Bets Win Bet
How
- Create index admin/user_bets
- Handle score and win/draw/lose in helper, handle list user_bets in controller
- Show list user bets win and list user bets win score

Show User Bets Win Bet

---

app/controllers/admin/soccer_matches_controller.rb
app/models/soccer_match.rb
app/views/admin/soccer_matches/_form.html.erb
app/views/admin/soccer_matches/_soccer_match.html.erb
app/views/admin/soccer_matches/edit.html.erb
app/views/admin/soccer_matches/new.html.erb
app/views/shared/_asider_admin.html.erb
app/views/soccer_matches/_soccer_match.html.erb
config/locales/en.yml
config/locales/vi.yml

- [#47143](https://edu-redmine.sun-asterisk.vn/issues/47143)
- [#47157](https://edu-redmine.sun-asterisk.vn/issues/47157)
What
- create soccer match
- update soccer match
How
- create and update soccer match by admin

Admin - soccer match

---

app/controllers/admin/payments_controller.rb
app/controllers/admin/user_bets_controller.rb
app/controllers/concerns/events_helper.rb
app/helpers/user_bets_helper.rb
app/models/user_bet.rb
app/views/admin/user_bets/_user_bet.html.erb
app/views/admin/user_bets/index.html.erb
config/locales/en.yml
config/locales/vi.yml
config/routes.rb

• [#47140](https://edu-redmine.sun-asterisk.vn/issues/47140)
What
- Handle Pay money for User bet win 
How
- Add controller create and create_all
- Handle pay money with create for 1 user
- Handle pay money all with create_all for all user
- Add link_to post in view index to controller create

Pay money for User bet Win

---

app/controllers/admin/user_bets_controller.rb
app/models/goal_result.rb
app/models/team.rb
app/models/team_tournament.rb
app/views/admin/soccer_matches/_soccer_match.html.erb
config/locales/en.yml
config/locales/vi.yml
db/seeds.rb

• [#47660](https://edu-redmine.sun-asterisk.vn/issues/47660)
What
-  Seed data and modify any code model, view, controller
How
- Seed data demo win bet
- Add any has_many in models
- modify button to dropdown in view admin home
- handle load bet in controller admin user_bet

Seed data and modify any code model, view, controller

---

.gitignore
app/controllers/admin/soccer_matches_controller.rb
app/controllers/concerns/events_helper.rb
app/models/soccer_match.rb
app/models/user_bet.rb
app/views/admin/soccer_matches/show.html.erb
config/locales/en.yml
config/locales/vi.yml
config/settings.yml
db/seeds.rb

• [#47723](https://edu-redmine.sun-asterisk.vn/issues/47723)
What
- statistic for a soccer match
How
- statistic by using the sum of the winner's money and the loser's money in a match
- create circle chart by javascipt in views side

statistic for a soccer match

---

app/controllers/admin/bets_controller.rb
app/controllers/admin/payments_controller.rb
app/controllers/concerns/events_helper.rb
app/models/soccer_match.rb
app/views/admin/bets/_bet_fields.html.erb
app/views/admin/bets/create.html.erb
app/views/admin/soccer_matches/_soccer_match.html.erb
config/locales/en.yml
config/locales/vi.yml
config/routes.rb
config/settings.yml
db/seeds.rb

• [#47147](https://edu-redmine.sun-asterisk.vn/issues/47147)
What
- Create bets for match
How
- Create method handle create all bets default for match if bets empty
- Show list bets
- Update list bets with nested attribute

Create bets for match

---

.framgia-ci.yml
.gitignore
.rspec
Gemfile
Gemfile.lock
app/controllers/admin/soccer_matches_controller.rb
app/models/soccer_match.rb
config/locales/en.yml
config/locales/vi.yml
spec/rails_helper.rb
spec/spec_helper.rb
spec/support/factory_bot.rb

• [#47854](https://edu-redmine.sun-asterisk.vn/issues/47854)
What
- Fix bugs
- add RSpec and some gems

Add RSpec to project

---

.framgia-ci.yml
.gitignore
Gemfile
Gemfile.lock
spec/controller/bets_controller_spec.rb
spec/controller/static_pages_controller_spec.rb
spec/factories/soccer_matchs.rb
spec/factories/users.rb
spec/rails_helper.rb

• [#47883](https://edu-redmine.sun-asterisk.vn/issues/47883)
What
- Rspec controller static_pages and controller bets

Rspec controller static_pages and bets

---

spec/controllers/currencies_controller_spec.rb
spec/shared_example/controller_spec.rb

• [#47962](https://edu-redmine.sun-asterisk.vn/issues/47962)
WHAT
- Write Rspec controller Curriencies
HOW
- create shared example
- Write Rspec controller Curriencies

Rspec for controller Curriencies

---

Gemfile
Gemfile.lock
spec/model/player_info_spec.rb
spec/model/player_spec.rb
spec/rails_helper.rb
spec/support/shoulda_matcher.rb

• [#47985](https://edu-redmine.sun-asterisk.vn/issues/47985)
WHAT
- Write RSpec for player model
- Write RSpec for player info model
HOW
- Create create model folder in spec
- Add gem shoulda matchers
- Create create player.rb and player_info.rb in model folder

[RSpec] player and player info model

---

app/models/tournament.rb
spec/factories/players.rb
spec/factories/teams.rb
spec/model/goal_result_spec.rb
spec/model/team_tournament_spec.rb
spec/model/tournament_spec.rb

• [#47988](https://edu-redmine.sun-asterisk.vn/issues/47988)
WHAT
- Rspec for model tournament, model team_tournament and model goals_result
HOW
- User gem "shoulda-matchers"
- Write Rspec for model tournament, model team_tournament and model goals_result

Rspec for model tournament and model team_tournament

---

app/controllers/admin/soccer_matches_controller.rb
app/models/user_bet.rb
config/locales/en.yml
config/locales/vi.yml
spec/controllers/admin/soccer_matches_controller_spec.rb
spec/model/comment_spec.rb
spec/model/currency_type_spec.rb
spec/model/news_spec.rb
spec/shared_example/controller_spec.rb

• [#48009](https://edu-redmine.sun-asterisk.vn/issues/48009)
WHAT
- Write RSpec for admin soccer match controller
HOW
- Create admin folder in spec/controller
- Create soccer_matches_controller_spec.rb in controller folder

[RSpec] [Admin] Soccer match controller

---

app/controllers/admin/base_controller.rb
spec/controllers/admin/user_bets_controller_spec.rb
spec/shared_example/controller_spec.rb

• [#48008](https://edu-redmine.sun-asterisk.vn/issues/48008)
WHAT
- Write Rspec for controller admin user_bets
HOW
- Write shared_example
- Write Rspec for controller admin user_bets
- modify flash in base_controller

Rspec for controller admin user_bets
